setData changed to setError
otherwise we got error "Uncaught TypeError: users.data?.map is not a function" 


Co-authored-by: Zubair <77893877+2u841r@users.noreply.github.com>